### PR TITLE
Make eauto recurse and reset mvars on failure

### PR DESCRIPTION
**Pull request by JLimperg**
Also various general improvements.

---

I'm procrastinating a difficult proof, so I continued a bit with the implementation of `eauto` and did some general polishing.

### CODE REVIEW

**Comment by lephe** [comment]
What a pleasant surprise, thanks! :D The little improvements are really useful as a guide.

I don't quite understand why you'd write `{e}` rather than `{← ppExpr e}` though. It doesn't substitute local declarations' expressions with their user-facing names, so now for example the constraints for `grewrite` look like this:

```
[Meta.Tactic.grewrite] Constraints to solve: 
      ?_uniq.302: relation.{0} (_uniq.216 -> Prop)
      ?_uniq.306: Proper.{0} (_uniq.216 -> Prop) ?_uniq.302 _uniq.239
      ?_uniq.308: relation.{0} Prop
      ?_uniq.318: Subrel.{0} (_uniq.216 -> Prop) ?_uniq.302 (respectful.{0 0} _uniq.216 Prop _uniq.223 ?_uniq.308)
      ?_uniq.330: Subrel.{0} Prop ?_uniq.308 (flip.{1 1 1} Prop Prop Prop impl) 
```
which is a lot more painful to debug. ^^"

**Comment by lephe** [comment]
I'm merging anyway so I can keep all the changes I tried on top of this. But if you have more details about `ppExpr`, I'd like to know.

**Comment by JLimperg** [comment]
I think `ppExpr` is a red herring. If you `trace[...] m!"{e}"`, where `e : Expr` and assuming you've previously used `withContext` to set a local context which contains the fvars in `e`, the hypotheses will be printed with pretty names as usual. Indeed, you can delete all the `ppExpr`s that currently remain in `Eauto.lean` with, as far as I can tell, no change in behaviour.

`ppExpr` may be useful if you're creating a `Format` or `MessageData` in one local context, then print it later in a different one. But the proper solution to this, afaiu, is to use `addMessageContext`, which embeds the current local context etc. in the resulting `MessageData` object.

**Comment by lephe** [comment]
I see now, I must be missing the proper `withContext`. I also noticed that with `m!"{e}"` I get the interactive type-checking whereas `ppExpr` just gives a string, so it's definitely the superior option.

**Comment by JLimperg** [comment]
Ah! I didn't even notice that in Emacs, but that's good to know.

**Pull request merged**
